### ISSUE TITLE
Slide Visibility

### ISSUE THREAD

**Issue by bob-fornal** [bob-fornal/talk--presentation-tool#1]
Need a means of turning a single slide on or off - to be used or not when presenting.

**Comment by adityaraute** [comment]
A button to toggle a simple pitch black overlay could work for this.

**Comment by bob-fornal** [comment]
I wish it were that simple. I've got an array of objects, each object representing a slide. I need a key/value pair (say `{ visible: false }`) indicating the slide should be skipped. Additionally, if the key does not exist, we'll treat it as if `visible` is `true`. This is just my reminder to wire it up. Thanks for the thought.

**Comment by adityaraute** [comment]
Oh, I again misinterpreted it.
I assumed it meant that you want to switch the presentation screen off (like professors do to handwrite some notes) and then turn it back on.

Your aim seems doable, too. I might have created a Pull Request, but I probably don't have the basic tech stack setup on my machine. Will try with GitPod.

**Comment by adityaraute** [comment]
Should the unit tests be another issue?

**Comment by bob-fornal** [comment]
> Should the unit tests be another issue?

Let me look at the current state of the Unit Tests. There should be tests against the code you merged in, but I will admit that I haven't kept up with the tests as well as I should have. I might have to get the test suite back into a working state before you can add tests for your recent commit. I'll send a note when it can be looked at.

**Comment by adityaraute** [comment]
Gotcha. Thanks! Will be looking forward to the same.

**Comment by bob-fornal** [comment]
OK.

I got the Unit Tests into a "non-broken" state. If you try `npm run test` or `ng test` now, there shouldn't be any failures. That doesn't mean that we have a high passing rate; I have some new code that doesn't have any testing at the moment. If you want to try to write tests against the code you merged, feel free.

**Comment by adityaraute** [comment]
Perfect, thanks a lot for the nudge! Is this the same change that you posted on your 100DaysOfCode campaign, too? I believe that circled around testing, too
