### ISSUE TITLE
SUGGESTION: Add a GitHub Workflow to run Unit Tests on every commit

### ISSUE THREAD

**Issue by adityaraute** [bob-fornal/talk--presentation-tool#10]
We can create a Workflow action file which runs our usual `npm run test` upon every commit to the `main` branch.
Could also run those checks for Pull Requests.

**Comment by bob-fornal** [comment]
I've been considering that. I want to ...

1. Integrate the tests into the PRs
2. Have a standard PR page that comes up.
3. Block push to main other than by PR.

I've got most of the code for this in other places ... let me track down some examples.

Feel free to tackle this once I get you the information.

**Comment by bob-fornal** [comment]
1. Here are the files for workflow: https://github.com/bob-fornal/100-Days-Of-Code--Tracker/tree/main/.github/workflows ... it's pretty clear which is for the on PR.
2. Here's the file that I use for PRs. It simply needs to be in the `.github` folder: https://github.com/bob-fornal/license-plate-game/blob/main/.github/pull_request_template.md
3. The key to this is the name in the above `on-pull-request.yml` file. 

![image](https://github.com/user-attachments/assets/4e9c8876-1413-4e89-a71d-b58d0571d5a3)

    a. In the project settings, these should be set to ensure approvals from code owners.
    
![image](https://github.com/user-attachments/assets/2dc8c5ca-a493-47c4-89b5-e068872f28d3)

    b. These are the settings to use the file above.

![image](https://github.com/user-attachments/assets/d1f7a285-43dd-4aef-8fe8-074866de657c)

    c. I would prefer these settings, as well.

![image](https://github.com/user-attachments/assets/11e8a268-927b-4ca7-abe1-38a8d288df5c)

**Comment by bob-fornal** [comment]
Feel free to implement these. Realize, they won't take effect until a PR is merged with these changes. So, feel free to open a second PR after these changes are implemented with some TINY change to see how it works.

**Comment by adityaraute** [comment]
The [Setup Node](https://github.com/marketplace/actions/setup-node-js-environment) workflow action requires the `package-lock.json` file to be committed. 

They recommend this for security reasons. You can check it here.
https://github.com/actions/setup-node?tab=readme-ov-file#checking-in-lockfiles


Do you think we should do this?

**Comment by bob-fornal** [comment]
I'm ok with that. For the purposes of this project it's not critical, but it is best to follow good practices. Good find!

**Comment by adityaraute** [comment]
Cheers! Will implement.
