### ISSUE TITLE
Unit Test for Visibility flag

### ISSUE THREAD

**Issue by adityaraute** [bob-fornal/talk--presentation-tool#7]
Furthering the discussion in #1

**Comment by adityaraute** [comment]
![image](https://github.com/user-attachments/assets/c40dd863-65b3-4b09-b382-3ef35f597dc6)

Chrome_ENV missing for test. I wonder if this is an issue from my GitPod environment's side and not from the project's.

**Comment by bob-fornal** [comment]
It looks like there's a question/answer for this ...

https://github.com/gitpod-io/gitpod/issues/962#issuecomment-562064877

**Comment by adityaraute** [comment]
I have looked at this, too. I tried several ways but they keep leading me to newer problems.
Here, for example, I can't install 'chromium' in Gitpod without using `snap` and Gitpod won't let me use `snap`, it's somewhat of a mess.
Allow me some time to figure those things out.

**Comment by adityaraute** [comment]
I have managed to run ChromeHeadless in my fork following this suggestion: https://github.com/gitpod-io/gitpod/issues/19342#issuecomment-2506164865

As expected, currently all tests pass successfully. I will now begin writing the tests for my component.

I have also had to make changes to some `.gitpod` files and need them to be committed to my fork. Would you rather not include those in your repo? I'll have to find a workaround if that's the case (which will be long, if at all possible)

**Comment by adityaraute** [comment]
Now that I look at it, I am wondering.
What should the unit test be?

Doesn't this cover everything?

```ts
  it('expects "getStructure" to set a talk structure', async () => {
    const folder: string = 'FOLDER';
    const talk: Structure = { ORDER: [], STYLE: [] };
    spyOn(service['http'], 'get').and.returnValue(of(talk));
    spyOn(service.structure, 'next').and.stub();

    await service.getStructure(folder);
    expect(service.structure.next).toHaveBeenCalledWith(talk);
  });
```

with respect to this function

```ts
  getStructure = async (folder: string): Promise<any> => {
    const structure: Structure = (await firstValueFrom(this.http.get(`./assets/talks/${ folder }/structure.json`)) as Structure);
    const tempStructure: Structure = { ORDER: [], STYLE: structure.STYLE };

    structure.ORDER.forEach((key: string) => {
      const objValue: StructureType = (structure[key] as StructureType);
      if (objValue.hasOwnProperty('visibility') === false || objValue.visibility === true) {
        tempStructure.ORDER.push(key);
        tempStructure[key] = structure[key];
      }
    });
    
    this.structure.next(tempStructure);
  };
```
